### ISSUE TITLE
not scanning input folder

### ISSUE THREAD

**Issue by blackerking** [adept/paperless-ocrmypdf#5]
I am trying to run the whole thing.
Everything works, except the input folder is not scanned.
it tells:
Setting up watches.
Watches established.

but it doesn't recognize any files.

**Comment by blackerking** [comment]
It seems not a problem of your docker:
http://blog.subjectify.us/miscellaneous/2017/04/24/docker-for-windows-watch-bindings.html

You may should add this as known problem.

**Comment by adept** [comment]
Oh, I was not aware of this aspect of Docker for Windows behavior. Thank you, I will mention this in the readme
